import { createEnum } from '@deip/toolbox';

const PROPOSAL_TYPES = createEnum({
  START_RESEARCH: 1,
  INVITE_MEMBER: 2,
  EXCLUDE_MEMBER: 3,
  SEND_FUNDS: 4,
  START_RESEARCH_TOKEN_SALE: 5,
  REBALANCE_RESEARCH_GROUP_TOKENS: 6,
  CHANGE_QUORUM: 7,
  CHANGE_RESEARCH_REVIEW_SHARE_PERCENT: 8,
  OFFER_RESEARCH_TOKENS: 9,
  CREATE_RESEARCH_MATERIAL: 10,
  CHANGE_RESEARCH_GROUP_META_DATA_TYPE: 11,
  CHANGE_RESEARCH_META_DATA_TYPE: 12
});

export {
  PROPOSAL_TYPES
};
