import { createEnum } from '@deip/toolbox';

const APP_EVENT = createEnum({
  PROJECT_CREATED: 1,
  PROJECT_UPDATED: 2,
  PROJECT_DELETED: 3,
  PROJECT_PROPOSAL_CREATED: 4,
  PROJECT_PROPOSAL_ACCEPTED: 5,
  PROJECT_PROPOSAL_DECLINED: 6,
  PROJECT_UPDATE_PROPOSAL_CREATED: 7,
  PROJECT_UPDATE_PROPOSAL_ACCEPTED: 8,
  PROJECT_UPDATE_PROPOSAL_DECLINED: 9,

  PROPOSAL_CREATED: 30,
  PROPOSAL_ACCEPTED: 31,
  PROPOSAL_DECLINED: 32,

  DAO_CREATED: 60,
  DAO_UPDATED: 61,
  DAO_MEMBER_REMOVED: 62,
  DAO_MEMBER_ADDED: 63,

  TEAM_INVITE_CREATED: 90,
  TEAM_INVITE_ACCEPTED: 91,
  TEAM_INVITE_DECLINED: 92,
  LEAVE_TEAM_CREATED: 93,
  LEAVE_TEAM_ACCEPTED: 94,
  LEAVE_TEAM_DECLINED: 95,

  TEAM_UPDATE_PROPOSAL_ACCEPTED: 120,
  TEAM_UPDATE_PROPOSAL_CREATED: 121,
  TEAM_UPDATE_PROPOSAL_DECLINED: 122,

  ATTRIBUTE_CREATED: 150,
  ATTRIBUTE_UPDATED: 151,
  ATTRIBUTE_DELETED: 152,
  ATTRIBUTE_SETTINGS_UPDATED: 153,

  PROJECT_TOKEN_SALE_PROPOSAL_CREATED: 180,
  PROJECT_TOKEN_SALE_PROPOSAL_ACCEPTED: 181,
  PROJECT_TOKEN_SALE_PROPOSAL_DECLINED: 182,

  INVESTMENT_OPPORTUNITY_CREATED: 200,
  INVESTMENT_OPPORTUNITY_PARTICIPATED: 201,

  FT_TRANSFERED: 230,
  FT_CREATED: 231,
  FT_ISSUED: 232,
  FT_TRANSFER_PROPOSAL_CREATED: 233,
  FT_TRANSFER_PROPOSAL_ACCEPTED: 234,
  FT_TRANSFER_PROPOSAL_DECLINED: 235,

  NFT_TRANSFERED: 260,
  NFT_CREATED: 262,
  NFT_ISSUED: 263,
  NFT_TRANSFER_PROPOSAL_CREATED: 264,
  NFT_TRANSFER_PROPOSAL_ACCEPTED: 265,
  NFT_TRANSFER_PROPOSAL_DECLINED: 266,

  TOKENS_SWAP_PROPOSAL_CREATED: 300,
  TOKENS_SWAP_PROPOSAL_ACCEPTED: 301,
  TOKENS_SWAP_PROPOSAL_DECLINED: 302,

  DOCUMENT_TEMPLATE_CREATED: 320,
  DOCUMENT_TEMPLATE_UPDATED: 321,
  DOCUMENT_TEMPLATE_DELETED: 322,

  PROJECT_CONTENT_DRAFT_CREATED: 350,
  PROJECT_CONTENT_DRAFT_UPDATED: 351,
  PROJECT_CONTENT_DRAFT_DELETED: 352,
  PROJECT_CONTENT_CREATED: 353,
  PROJECT_CONTENT_STATUS_UPDATED: 354,
  PROJECT_CONTENT_METADATA_UPDATED: 355,
  PROJECT_CONTENT_PROPOSAL_CREATED: 356,
  PROJECT_CONTENT_PROPOSAL_ACCEPTED: 357,
  PROJECT_CONTENT_PROPOSAL_DECLINED: 358,

  REVIEW_REQUEST_CREATED: 380,
  REVIEW_REQUEST_DECLINED: 381,
  REVIEW_CREATED: 382,
  UPVOTED_REVIEW: 383,

  PROJECT_NDA_CREATED: 400,
  PROJECT_NDA_PROPOSAL_CREATED: 401,
  PROJECT_NDA_PROPOSAL_ACCEPTED: 402,
  PROJECT_NDA_PROPOSAL_DECLINED: 403,

  CONTRACT_AGREEMENT_CREATED: 430,
  CONTRACT_AGREEMENT_PROPOSAL_CREATED: 431,
  CONTRACT_AGREEMENT_PROPOSAL_ACCEPTED: 432,
  CONTRACT_AGREEMENT_PROPOSAL_DECLINED: 433,
  CONTRACT_AGREEMENT_ACCEPTED: 434,
  CONTRACT_AGREEMENT_REJECTED: 435,

  LAYOUT_SETTINGS_UPDATED: 460,
  LAYOUT_CREATED: 461,
  LAYOUT_UPDATED: 462,
  LAYOUT_DELETED: 463,

  PORTAL_PROFILE_UPDATED: 480,
  PORTAL_SETTINGS_UPDATED: 481,
  NETWORK_SETTINGS_UPDATED: 482,

  USER_PROFILE_DELETED: 500,
  USER_AUTHORITY_ALTERED: 501,

  BOOKMARK_CREATED: 520,
  BOOKMARK_DELETED: 521,
  NOTIFICATIONS_MARKED_AS_READ: 522
});

export {
  APP_EVENT
};
