const NUMBER_OF_STEPS = 6;
const MIN_TOKEN_UNITS_TO_SELL = 100;
const DEFAULT_PRECISION = 0;
const DEFAULT_AMOUNT = 10000;

export {
  NUMBER_OF_STEPS,
  MIN_TOKEN_UNITS_TO_SELL,
  DEFAULT_PRECISION,
  DEFAULT_AMOUNT
};
