import { createEnum } from '@deip/toolbox';

const ECI_REWARD_ACTION_TYPES = {
  CONTENT: 'content',
  REVIEW: 'review',
  INIT: 'init'
};

const ACTIONS_MAP = {
  1: ECI_REWARD_ACTION_TYPES.CONTENT,
  2: ECI_REWARD_ACTION_TYPES.REVIEW,
  3: ECI_REWARD_ACTION_TYPES.INIT
};

const USER_NOTIFICATION_STATUS = createEnum({
  UNREAD: 1,
  READ: 2
});

const USER_PROFILE_STATUS = createEnum({
  PENDING: 1,
  APPROVED: 2
});

const USER_BOOKMARK_TYPE = createEnum({
  PROJECT: 1
});

const USER_NOTIFICATION_TYPE = createEnum({
  PROPOSAL: 1,
  PROPOSAL_ACCEPTED: 2,
  INVITATION: 3,
  INVITATION_APPROVED: 4,
  INVITATION_REJECTED: 5,
  EXCLUSION_APPROVED: 6,
  PROJECT_CONTENT_EXPERT_REVIEW: 7,
  PROJECT_CONTENT_EXPERT_REVIEW_REQUEST: 8,
  PROJECT_NDA_PROPOSED: 9,
  PROJECT_NDA_SIGNED: 10,
  PROJECT_NDA_REJECTED: 11
});

export {
  ECI_REWARD_ACTION_TYPES,
  ACTIONS_MAP,
  USER_NOTIFICATION_STATUS,
  USER_NOTIFICATION_TYPE,
  USER_PROFILE_STATUS,
  USER_BOOKMARK_TYPE
};
