const ECI_REWARD_ACTION_TYPES = {
  CONTENT: 'content',
  REVIEW: 'review',
  INIT: 'init'
};

const ACTIONS_MAP = {
  1: ECI_REWARD_ACTION_TYPES.CONTENT,
  2: ECI_REWARD_ACTION_TYPES.REVIEW,
  3: ECI_REWARD_ACTION_TYPES.INIT
};

export {
  ECI_REWARD_ACTION_TYPES,
  ACTIONS_MAP
};
